import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { render } from "@react-email/components";
import WelcomeEmail from "../../emails/WelcomeTemplate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const html = render(<WelcomeEmail />, {
        pretty: true,
    });
  
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
